In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
import pandas as pd
import numpy as nm
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
data = pd.read_csv("../input/graduate-admissions/Admission_Predict.csv")
data

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65
...,...,...,...,...,...,...,...,...,...
395,396,324,110,3,3.5,3.5,9.04,1,0.82
396,397,325,107,3,3.0,3.5,9.11,1,0.84
397,398,330,116,4,5.0,4.5,9.45,1,0.91
398,399,312,103,3,3.5,4.0,8.78,0,0.67
399,400,333,117,4,5.0,4.0,9.66,1,0.95

In [4]:
verify = pd.read_csv("../input/graduate-admissions/Admission_Predict_Ver1.1.csv")
verify

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65
...,...,...,...,...,...,...,...,...,...
495,496,332,108,5,4.5,4.0,9.02,1,0.87
496,497,337,117,5,5.0,5.0,9.87,1,0.96
497,498,330,120,5,4.5,5.0,9.56,1,0.93
498,499,312,103,4,4.0,5.0,8.43,0,0.73
499,500,327,113,4,4.5,4.5,9.04,0,0.84

In [5]:
data.count()

Serial No.           400
GRE Score            400
TOEFL Score          400
University Rating    400
SOP                  400
LOR                  400
CGPA                 400
Research             400
Chance of Admit      400
dtype: int64

In [6]:
from sklearn.model_selection import train_test_split

y=data[data.columns[8]].values;
X=data[data.columns[[1,2,3,4,5,6,7]]].values

print(X.shape)
print(y.shape)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

print(X_train.shape)
print(X_test.shape)

(400, 7)
(400,)
(320, 7)
(80, 7)

In [8]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error

model=RandomForestRegressor()
model.fit(X_train,y_train)

y_pred=model.predict(X_test)
print("Accuracy: ", model.score(X_test,y_test))

print("MSE: ", mean_squared_error(y_pred,y_test))
print("RMSE: ", nm.sqrt(mean_squared_error(y_pred,y_test)))

Accuracy:  0.8384071592344193
MSE:  0.003294837624999997
RMSE:  0.05740067617197551

In [10]:
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X_train,y_train)

y_pred=model.predict(X_test)
print("Accuracy: ", model.score(X_test,y_test))


print("MSE: ", mean_squared_error(y_pred,y_test))
print("RMSE: ", nm.sqrt(mean_squared_error(y_pred,y_test)))

Accuracy:  0.865651638032326
MSE:  0.002739329513430379
RMSE:  0.052338604427615176

In [11]:
from sklearn.model_selection import train_test_split

y1=verify[verify.columns[8]].values;
X1=verify[verify.columns[[1,2,3,4,5,6,7]]].values

print(X1.shape)
print(y1.shape)

X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size=0.2)

print(X1_train.shape)
print(X1_test.shape)

(500, 7)
(500,)
(400, 7)
(100, 7)

In [12]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error

model=RandomForestRegressor()
model.fit(X1_train,y1_train)

y1_pred=model.predict(X1_test)
print("Accuracy: ", model.score(X1_test,y1_test))

print("MSE: ", mean_squared_error(y1_pred,y1_test))
print("RMSE: ", nm.sqrt(mean_squared_error(y1_pred,y1_test)))

Accuracy:  0.8154434756106785
MSE:  0.0034153366000000043
RMSE:  0.058440881239077876

In [13]:
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X1_train,y1_train)

y1_pred=model.predict(X1_test)
print("Accuracy: ", model.score(X1_test,y1_test))


print("MSE: ", mean_squared_error(y1_pred,y1_test))
print("RMSE: ", nm.sqrt(mean_squared_error(y1_pred,y1_test)))

Accuracy:  0.8297159755678777
MSE:  0.00315121485389206
RMSE:  0.05613568253697518